import { GuardrailPolicy } from '../types';

export const DEFAULT_POLICIES: GuardrailPolicy[] = [
  {
    id: 'pol-inj-01',
    name: 'Protect System Instructions & Guardrail Integrity',
    description: 'Immediately block user prompts or retrieved contexts attempting to override system rules, simulate jailbreaks, or ignore developer directives.',
    category: 'injection',
    riskLevel: 'CRITICAL',
    action: 'BLOCK',
    enabled: true,
  },
  {
    id: 'pol-ctx-02',
    name: 'Block Untrusted Injected Context',
    description: 'Reject context documents containing suspicious hidden commands, untrusted scrapings, or unauthorized instructions before agent reasoning.',
    category: 'context',
    riskLevel: 'HIGH',
    action: 'BLOCK',
    enabled: true,
  },
  {
    id: 'pol-exf-03',
    name: 'Prevent Credential & Secret Exfiltration',
    description: 'Intercept any user query or model response attempting to output API keys, environment tokens, private DB connection strings, or system prompts.',
    category: 'exfiltration',
    riskLevel: 'CRITICAL',
    action: 'BLOCK',
    enabled: true,
  },
  {
    id: 'pol-tool-04',
    name: 'Enforce Least-Privilege Tool Execution',
    description: 'Verify tool requests before invocation. Destructive operations (drop tables, delete files, arbitrary shell exec, credential export) are blocked.',
    category: 'tool',
    riskLevel: 'CRITICAL',
    action: 'BLOCK',
    enabled: true,
  },
  {
    id: 'pol-conf-05',
    name: 'Flag Conflicting Knowledge Sources',
    description: 'Warn and downgrade reliability when two retrieved knowledge chunks contain mutually contradictory claims on critical policies.',
    category: 'evidence',
    riskLevel: 'MEDIUM',
    action: 'WARN',
    enabled: true,
  },
  {
    id: 'pol-evid-06',
    name: 'Require Evidence Grounding for Factual Answers',
    description: 'Flag responses that assert factual claims without supporting evidence from trusted knowledge sources.',
    category: 'evidence',
    riskLevel: 'MEDIUM',
    action: 'WARN',
    enabled: true,
  },
  {
    id: 'pol-rel-07',
    name: 'Enforce Minimum Reliability Threshold',
    description: 'Trigger a human review if the aggregate Agent Reliability Score falls below 70.',
    category: 'reliability',
    riskLevel: 'HIGH',
    action: 'REVIEW',
    enabled: true,
  },
];
